---
engines:
  duplication:
    enabled: true
  eslint:
    enabled: true
    channel: "eslint-5"
    checks:
      import/no-unresolved:
        enabled: false
      import/extensions:
        enabled: false
    config:
      extensions:
      - .js
ratings:
  paths:
  - "**.js"
exclude_patterns:
- node_modules/
- test/