env:
  browser: true
  commonjs: true
  es6: true
extends:
  - airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
plugins:
  - react
rules: {
  'no-underscore-dangle': [0],
  'react/jsx-filename-extension': [0],
  "import/no-extraneous-dependencies": ["error", {"devDependencies": ["**/test/**/*.js"]}],
  'class-methods-use-this': [0],
  'no-throw-literal': [0],
  'comma-dangle': ['error',
    {
      arrays: 'always-multiline',
      objects: 'always-multiline',
      imports: 'always-multiline',
      exports: 'always-multiline',
      functions: 'never',
    },
  ],
  "prefer-destructuring": ["error", {
    "array": false,
    "object": false,
  }, {
    "enforceForRenamedProperties": false
  }],
}
