sudo: required
language: node_js
deploy:
  edge: true
  provider: cloudfoundry
  username: deploy-federalist
  password:
    secure: sLw6BSkVU9OUTJmZ6EysgAr+WtdIvSuo+b+bZ2Zk6wk4ayt+NWVcSYqkdkFH5spQ+pUWb1VgOWxFltlNhhkgzgDBxTOMehhKJ0/X/s0RJPdd16oX6kCBjxvJLesC9dXQG3zjuw5F51IXIqaQJfCP8/MtAL/LPxOeZL87dBHaj1QZGY4g90zfAM5WTS3zlgKCNq2KDXPKou4IboPVfZ16HGFdwxmnL9XNOtHOMd1Uutk8gGyeIi83gpqEzpiGYGAn6qYIBZf9XxhG7Iv+cH2arb1nKvERyp9/5GJBo1u0eAnjUu/9qR5BLEixHNwwC2DyaCgeBUz087M9pqpsWqXV0OSHbYkpBz3R8/bagmj3wLb5/yDRFy2xRpmkVDO0pH0NkEv0ldos3p+0d8++sPk15L/UsTlzxe84YhOI+Aqd3dpXwyZk/Gdd5C+vc2IYpGDlJeIolvDIjhLbIzmWBtz909YJMEdIckYxqmJxm9AEJ5JovLswN5u0ZSBX01Mus3ZuhliFD2vJU473nUnljW99pHaqe0z0EKyMDCclgPcK8IohS5OsBizhOzHbGrKU97mVPHx7wP31zltJgO59BO99/aaL9u9oIf8JJT/N4EOWSRtH74/46E2Yhc7vh+IjcWwn53EqCN24d1oZ9//hOC/BYX7uwJ9uevEK0c4CvJarfQ4=
  api: https://api.cloud.gov
  organization: federalist
  space: prod
  on:
    branch: master
