language: node_js
sudo: true
cache:
  yarn: true
node_js:
- 6.9
env:
  global:
  - CF_API=https://api.fr.cloud.gov
  - CF_ORGANIZATION=gsa-18f-federalist
  - YARN_VERSION=0.24.6-1
before_install:
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn=$YARN_VERSION
install:
  - yarn --pure-lockfile
script:
  - yarn eslint
  - yarn test
before_deploy:
  - export PATH=$HOME:$PATH
  - travis_retry curl -L -o $HOME/cf.tgz "https://cli.run.pivotal.io/stable?release=linux64-binary&version=6.23.1"
  - tar xzvf $HOME/cf.tgz -C $HOME
  - travis_retry cf install-plugin autopilot -f -r CF-Community
deploy:
  - provider: script
    script: scripts/deploy-travis.sh
    on:
      branch: master
  - provider: script
    script: scripts/deploy-travis.sh
    on:
      branch: staging
