language: node_js
sudo: true
node_js:
- "4.2.3"
env:
  global:
  - CF_APP=federalist-builder
  - CF_API=https://api.cloud.gov
  - CF_USERNAME=deploy-federalist
  - CF_ORGANIZATION=federalist
  - CF_SPACE=prod
  - secure: "As7Hpdto8dV5v6dtPrtSKGDD4sSkYDm9UYgQAKXWeRVUGp5eKOsoxEaSIjDyEpLgHkoPZTa+QxYzzYpbPIfjJClqwoUvmRIUT2Jc06Xg7id6OeXf+3u73F6AdXkai9qi+MlLzxt/uxs037lUZvqErPV/k/2Rj8JPBEYRiCMo8riAU6E9H1gH2e1GGnOrH3LPDCv95WA8+KYvMB4j5vQrMb8zOfDPVhcBp0omYlLR0P97vtY5SlcMQgkBYBsVJeJQLZt2k/ri24pqspBS1Sw8SXft0V2gngapCKRuq4AvgjMhhYphiW2S/wIQof0hDIwPX+Dc1xFdDvvFHox4SY1XMogXsED7Q3afCg+d6lns3vgs9gLrLoFklcj+/HbXoQ1aDq6ctIX6nsZ53U0gx2LHmfFW/+T2RWSHt9VWzrDWBgmq8j1CH5tcx3l0jsjfjHGeEL9W8OTbEt4tp8gyYXvVt4W0lUAp+1yoB//BMmBI6WHAONGL+uy+usIbf9qq9I5IQ03KdpS7cBZ3sDmbRVegxMPQzOxTIIB0CFUSZALkjYCkyXoUysh5sFmtHJP8bweeXR5F8zVnLLPmBbfyz4cVttHNwIBOU25rTD7MEEj+s7KDPeC/fJ+7IqVkD8lw6HYKDtoncOzPMAp2JfP1ezCYUPiXCJuj+i0w36RtlGmXgN4="
before_deploy: npm install -g https://github.com/18F/cf-blue-green/tarball/master
deploy:
  provider: script
  script: cf-blue-green-travis
  on:
    branch: master
