language: node_js
sudo: true
node_js:
- 6.9
env:
  global:
  - CF_API=https://api.fr.cloud.gov
  - CF_USERNAME=gsa-18f-federalist_deployer
  - CF_ORGANIZATION=gsa-18f-federalist
  # CF_PASSWORD for gsa-18f-federalist_deployer user
  - secure: "ovjRuWHniFKz+Yr6eOO89E8LZhxs1BRdqpGdljZnf70XsdoldqdVN0Lr0Vd1zJMD/ep5TPfaT9h4VADB9JqMF1ODWmX7LiJ2W7GP309S9KWDUkUbl5xOp4mCMl0XDlStwLZeIcPt6Oa2UpSQCnjFMUK1KLBEGC/8vxtp4X18VjPmZ2V9Uu6lMB6Fe2fZbx7N7QWsQjciwUd1bVyseIMHCSGWeZ3OZARxBsfJT7ZwHX5zD8xT3IfHSUArDhYYM5+Q/ApP+MK3N9gZXukKeq6/2V4t8WNuCPEqcJH/eRBKu5IS/ddk09KXWS51aMdU0zC4/LL/sSvOsdufPf+e6Ha2RZV+6BoWFFSZKRWpCSpVNj6ORSGICCudFtC4oIJaTKB1qqcAjT/fB7iuHsWnymUNTpHDIAeuOA4kvwTLG0LnrPxfe6Midpx4ceYb+Jv0BIosVKK2ZoLsQDSGgOLYvhw4nhzqbo8jHkmq8PhZUODiK7vlwIZWwnFkvqkmKHEKILeTikZ4Gx5DWbMB/AAlp/NSLZHVRz+ARKZ3qKe5wUgDkbkCuDqEOq7xnUN8g05Kp8NlIbEI7JJjrgbSfjBUqApTLyjwEx94bw6Wo7iVexBzW0l+TsoIiI5FkgWFrM8YFXEunBpwMpzJ6fr0EMFWnxzVvH8yhMewS7O1tn+gqhPtoNg="
before_deploy:
  - export PATH=$HOME:$PATH
  - travis_retry curl -L -o $HOME/cf.tgz "https://cli.run.pivotal.io/stable?release=linux64-binary&version=6.23.1"
  - tar xzvf $HOME/cf.tgz -C $HOME
  - travis_retry cf install-plugin autopilot -f -r CF-Community
deploy:
  - provider: script
    script: scripts/deploy-travis.sh
    on:
      branch: master
  - provider: script
    script: scripts/deploy-travis.sh
    on:
      branch: staging
