---
applications:
- name: federalist-builder-dev
  routes:
  - route: federalist-builder-dev.fr.cloud.gov
  disk_quota: 512M
  memory: 128MB
  instances: 1
  services:
  - federalist-dev-sqs-creds
  - federalist-deploy-user
  env:
    BUILD_CONTAINER_BASE_NAME: "federalist-build-container-dev"
    BUILD_TIMEOUT_SECONDS: 600 # 10 * 60 seconds = 10 minutes
    CLOUD_FOUNDRY_OAUTH_TOKEN_URL: "https://login.fr.cloud.gov/oauth/token"
    LOG_LEVEL: "verbose"
    NUM_BUILD_CONTAINERS: 1
