---
applications:
- name: federalist-builder-dev
  domain: fr.cloud.gov
  hostname: federalist-builder-dev
  disk_quota: 512M
  memory: 128MB
  instances: 1
  services:
  - federalist-dev-sqs-creds
  - federalist-deploy-user
  env:
    BUILD_TIMEOUT_SECONDS: 600 # 10 * 60 seconds = 10 minutes
    BUILD_CONTAINER_DOCKER_IMAGE_NAME: "federalist-registry-staging.fr.cloud.gov/federalist-garden-build-dev"
    CLOUD_FOUNDRY_OAUTH_TOKEN_URL: "https://login.fr.cloud.gov/oauth/token"
    EXPECTED_NUM_BUILD_CONTAINERS: 1
    LOG_LEVEL: "verbose"
